---

version: '3.2'
services:
  developer-portal-backend:
    container_name: developer-portal-backend
    image: pagopa/io-developer-portal-backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
