---

version: '3.2'
services:
  developer-portal-backend:
    container_name: developer-portal-backend
    image: teamdigitale/digital-citizenship-onboarding
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
